### PR TITLE
Fix the output of total loss to represent the actual optimized term.

### PR DESCRIPTION
**Pull request by Tilps**

### CODE REVIEW

**Comment by mooskagh** [comment]
What was that about? Looks like adding some random constant without anyone to review/agree.

**Comment by dubslow** [comment]
It was sitting here for several days waiting for anyone at all to review... and no one did

**Comment by mooskagh** [comment]
Catch random passer-bys on #dev and #technical. :)

**Comment by dubslow** [comment]
He tried! twice a day every day.

**Comment by Tilps** [comment]
This was reviewed by KillerDucky - this constant actually makes the massive comment above the line be true - MSE sent to the averager is divided by 4, but the 'loss' which is optimized doesn't have that divide by 4 in place.  This multiplier undoes that so that the total loss actually represents the optimized term.

**Pull request merged**
