### PR TITLE
Disable redundant gammas and add softmax feeding bias regularization.

### PR DESCRIPTION
**Pull request by Tilps**
I don't think these really need to be optional, so I didn't bother adding options.

### CODE REVIEW

**Comment by Ttl** [comment]
I'm not really convinced that this is necessary and I don't think there is yet any convincing evidence either way for this.

The gammas after the first convolution in residual block and the ones in the heads are redundant and can be safely fixed to 1. They can merged through relu to the weights of the next layer. For that reason it feels weird to make them go to zero with regularization. If there is any possible issue with them I would rather fix them to 1 than apply regularization to them.

**Comment by Tilps** [comment]
I also think fixing unneeded gammas would be better - I've not checked how easy that is to implement. (IE does the gamma weight go away entirely if I disable scale parameter.)

**Comment by Tilps** [comment]
Disabling scale removes the variable - but I've kept it to keep the load/save code simple.  I also kept the name the same for consistency in the tensorboard.

Unfortunately net_to_model doesn't work for any old nets since they'll try and populate the unused gammas with non-unity values. Thus there is no way to migrate to this script from old versions.
I hope to write a gamma propagate function - but its far from trivial - so its not included here.

**Comment by ASilver** [comment]
Does Leela Zero have this issue? I saw some ranking with a 256x20 SE net, but don't know if it was Leela, or another project.

**Comment by Tilps** [comment]
Added gammas back to the initial convolution - since in the case input gammas would like to go to 0, the equivalent network with unit gammas has the gammas of residual block outputs going to infinity.  If there isn't a need for directly calculating 256 local values from the input they are forced to become a component of calculations that are not desired since actually getting the other gammas to go to infinity won't actually work.
This may imply that we should have some kind of regularization of the remaining gammas since they are still trivially infinite equal minimal loss solutions just by messing with the remaining gammas a little bit.

**Comment by Tilps** [comment]
I'm merging this for T51.

**Pull request merged**
